 const packages = [
    {
        "id": "1",
        "url": "https://images.unsplash.com/photo-1722232581651-d87e4099561b?q=80&w=2012&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "category": "Adventure",
        "country": "India",
        "placeName": "Ladakh",
        "bestseller": true,
        "instantBooking": true,
        "rating": 4.5,
        "price": "$499",
        "discount": "60% off",
        "images": [
            "https://images.unsplash.com/photo-1707343848552-893e05dba6ac?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "https://images.unsplash.com/photo-1530789253388-582c481c54b0?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "https://images.unsplash.com/photo-1473163928189-364b2c4e1135?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "https://plus.unsplash.com/premium_photo-1675484743423-57da4e8011c2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D",
            "https://plus.unsplash.com/premium_photo-1675484743423-57da4e8011c2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D"
        ],
        "highlights": ["Scenic views", "Mountain treks", "Local culture", "Buddhist Monasteries", "Stunning landscapes"],
        "duration": "7 days, 6 nights",
        "itinerary": ["Day 1: Arrival", "Day 2: Sightseeing", "Day 3: Nubra Valley", "Day 4: Pangong Lake", "Day 5: Return to Leh", "Day 6: Free Day", "Day 7: Departure"],
        "inclusions": ["Accommodation", "Breakfast", "Guided tours", "Transport within Ladakh", "Permits", "Entry fees"],
        "exclusions": ["Flights", "Personal expenses", "Travel insurance", "Meals not specified", "Tips", "Adventure activities"]
    },
    {
        "id": "2",
        "url": "https://picsum.photos/id/19/700/900",
        "category": "Beach",
        "country": "Thailand",
        "placeName": "Phuket",
        "bestseller": true,
        "instantBooking": true,
        "rating": 4.7,
        "price": "$599",
        "discount": "50% off",
        "images": [
            "https://picsum.photos/id/19/700/900",
            "https://picsum.photos/id/20/700/900",
            "https://picsum.photos/id/21/700/900",
            "https://picsum.photos/id/22/700/900",
            "https://picsum.photos/id/23/700/900"
        ],
        "highlights": ["Crystal clear waters", "Vibrant nightlife", "Island hopping", "Snorkeling and diving", "Beachfront resorts"],
        "duration": "5 days, 4 nights",
        "itinerary": ["Day 1: Arrival", "Day 2: Phi Phi Islands Tour", "Day 3: James Bond Island", "Day 4: Free Day", "Day 5: Departure"],
        "inclusions": ["Accommodation", "Breakfast", "Island tours", "Snorkeling gear", "Airport transfers"],
        "exclusions": ["Flights", "Personal expenses", "Travel insurance", "Meals not included", "Optional tours", "Alcoholic beverages"]
    },
    {
        "id": "3",
        "url": "https://picsum.photos/id/12/700/900",
        "category": "Cultural",
        "country": "Japan",
        "placeName": "Kyoto",
        "bestseller": false,
        "instantBooking": true,
        "rating": 4.8,
        "price": "$799",
        "discount": "40% off",
        "images": [
            "https://picsum.photos/id/12/700/900",
            "https://picsum.photos/id/15/700/900",
            "https://picsum.photos/id/16/700/900",
            "https://picsum.photos/id/17/700/900",
            "https://picsum.photos/id/18/700/900"
        ],
        "highlights": ["Historic temples", "Traditional tea ceremonies", "Geisha performances", "Cherry blossoms", "Zen gardens"],
        "duration": "6 days, 5 nights",
        "itinerary": ["Day 1: Arrival", "Day 2: Kiyomizu-dera Temple", "Day 3: Arashiyama Bamboo Grove", "Day 4: Fushimi Inari Shrine", "Day 5: Nijo Castle", "Day 6: Departure"],
        "inclusions": ["Accommodation", "Breakfast", "Guided tours", "Entry fees", "Local transportation"],
        "exclusions": ["Flights", "Personal expenses", "Travel insurance", "Meals not specified", "Optional activities"]
    },
    {
        "id": "4",
        "url": "https://picsum.photos/id/29/700/900",
        "category": "Safari",
        "country": "Kenya",
        "placeName": "Masai Mara",
        "bestseller": true,
        "instantBooking": true,
        "rating": 4.9,
        "price": "$1,299",
        "discount": "30% off",
        "images": [
            "https://picsum.photos/id/29/700/900",
            "https://picsum.photos/id/25/700/900",
            "https://picsum.photos/id/26/700/900",
            "https://picsum.photos/id/27/700/900",
            "https://picsum.photos/id/28/700/900"
        ],
        "highlights": ["Big Five game viewing", "Wildebeest migration", "Luxury camps", "Cultural visits", "Hot air balloon rides"],
        "duration": "5 days, 4 nights",
        "itinerary": ["Day 1: Arrival", "Day 2: Game Drive", "Day 3: Maasai Village Visit", "Day 4: Hot Air Balloon Safari", "Day 5: Departure"],
        "inclusions": ["Accommodation", "Meals", "Game drives", "Park fees", "Cultural activities"],
        "exclusions": ["Flights", "Personal expenses", "Travel insurance", "Alcoholic beverages", "Tips"]
    },
    {
        "id": "5",
        "url":  "https://picsum.photos/id/38/700/900",
        "category": "City Break",
        "country": "France",
        "placeName": "Paris",
        "bestseller": true,
        "instantBooking": true,
        "rating": 4.6,
        "price": "$899",
        "discount": "45% off",
        "images": [
            "https://picsum.photos/id/31/700/900",
            "https://picsum.photos/id/33/700/900",
            "https://picsum.photos/id/35/700/900",
            "https://picsum.photos/id/37/700/900",
            "https://picsum.photos/id/38/700/900"
        ],
        "highlights": ["Eiffel Tower", "Louvre Museum", "Seine River Cruise", "Montmartre", "Notre-Dame Cathedral"],
        "duration": "4 days, 3 nights",
        "itinerary": ["Day 1: Arrival", "Day 2: Eiffel Tower & Seine Cruise", "Day 3: Louvre Museum", "Day 4: Departure"],
        "inclusions": ["Accommodation", "Breakfast", "City tours", "Museum tickets", "Cruise tickets"],
        "exclusions": ["Flights", "Personal expenses", "Travel insurance", "Meals not included", "Optional tours"]
    },
    {
        "id": "6",
        "url": "https://picsum.photos/id/81/700/900",
        "category": "Nature",
        "country": "Canada",
        "placeName": "Banff",
        "bestseller": true,
        "instantBooking": true,
        "rating": 4.7,
        "price": "$999",
        "discount": "35% off",
        "images": [
           "https://picsum.photos/id/91/700/900",
            "https://picsum.photos/id/13/700/900",
            "https://picsum.photos/id/42/700/900",
            "https://picsum.photos/id/47/700/900",
            "https://picsum.photos/id/38/700/900"
        ],
        "highlights": ["Rocky Mountains", "Lake Louise", "Banff National Park", "Wildlife spotting", "Hiking trails"],
        "duration": "6 days, 5 nights",
        "itinerary": ["Day 1: Arrival", "Day 2: Banff National Park", "Day 3: Lake Louise", "Day 4: Wildlife Safari", "Day 5: Free Day", "Day 6: Departure"],
        "inclusions": ["Accommodation", "Breakfast", "Park fees", "Guided tours", "Transport"],
        "exclusions": ["Flights", "Personal expenses", "Travel insurance", "Meals not specified", "Optional activities"]
    },{
        "id": "7",
        "url": "https://picsum.photos/id/91/700/900",
        "category": "Nature",
        "country": "Canada",
        "placeName": "Banff",
        "bestseller": true,
        "instantBooking": true,
        "rating": 4.7,
        "price": "$599",
        "discount": "35% off",
        "images": [
           "https://picsum.photos/id/31/700/900",
            "https://picsum.photos/id/53/700/900",
            "https://picsum.photos/id/95/700/900",
            "https://picsum.photos/id/42/700/900",
            "https://picsum.photos/id/45/700/900"
        ],
        "highlights": ["Rocky Mountains", "Lake Louise", "Banff National Park", "Wildlife spotting", "Hiking trails"],
        "duration": "6 days, 5 nights",
        "itinerary": ["Day 1: Arrival", "Day 2: Banff National Park", "Day 3: Lake Louise", "Day 4: Wildlife Safari", "Day 5: Free Day", "Day 6: Departure"],
        "inclusions": ["Accommodation", "Breakfast", "Park fees", "Guided tours", "Transport"],
        "exclusions": ["Flights", "Personal expenses", "Travel insurance", "Meals not specified", "Optional activities"]
    },{
        "id": "8",
        "url": "https://picsum.photos/id/65/700/900",
        "category": "Nature",
        "country": "Canada",
        "placeName": "Banff",
        "bestseller": true,
        "instantBooking": true,
        "rating": 4.7,
        "price": "$1,599",
        "discount": "35% off",
        "images": [
           "https://picsum.photos/id/71/700/900",
            "https://picsum.photos/id/93/700/900",
            "https://picsum.photos/id/45/700/900",
            "https://picsum.photos/id/87/700/900",
            "https://picsum.photos/id/58/700/900"
        ],
        "highlights": ["Rocky Mountains", "Lake Louise", "Banff National Park", "Wildlife spotting", "Hiking trails"],
        "duration": "6 days, 5 nights",
        "itinerary": ["Day 1: Arrival", "Day 2: Banff National Park", "Day 3: Lake Louise", "Day 4: Wildlife Safari", "Day 5: Free Day", "Day 6: Departure"],
        "inclusions": ["Accommodation", "Breakfast", "Park fees", "Guided tours", "Transport"],
        "exclusions": ["Flights", "Personal expenses", "Travel insurance", "Meals not specified", "Optional activities"]
    }];
  export default packages;